In [7]:
from preprocessing_photos import *

In [3]:
import pandas as pd

In [10]:
path = RAW_DATA_PATH
DATASET_TRAIN_INTERACTION = 'train_interaction.txt'
columns = ['user_id', 'photo_id', 'click', 'like', 'follow', 'time', 'playing_time', 'duration_time']
train_interaction = pd.read_table(os.path.join(path, DATASET_TRAIN_INTERACTION), header=None)
train_interaction.columns = columns
users = set(train_interaction['user_id'])
print(len(users))
labels = np.any(train_interaction[['click', 'like', 'follow']], axis=1)
print('#pos={}, #tot={}, ratio={}%'.format(np.sum(labels), len(labels), np.sum(labels)/len(labels) * 100))

37821


#pos=10547052, #tot=52134536, ratio=20.230451461196473%


In [24]:
from matplotlib import pyplot as plt
unique, counts = np.unique(train_interaction['user_id'], return_counts=True)
plt.hist(counts, bins=len(unique), range=[0, 5000])
plt.show()

In [25]:
plt.hist(counts, bins=len(unique), range=[0, 5000])
plt.show()

In [26]:
import numpy as np

In [29]:
r_arr = np.random.randint(0, 10, 20)
print(r_arr)
arg_sort = np.argsort(r_arr)
print(arg_sort)
top20 = arg_sort[int(len(r_arr) * 0.8):]
print(top20)
print(r_arr[top20])


[3 8 7 3 2 7 5 7 3 1 9 7 7 7 2 0 7 6 8 8]
[15  9 14  4  8  0  3  6 17  7 11 12 13  2 16  5 18  1 19 10]
[18  1 19 10]
[8 8 8 9]


In [40]:
with open('datahouse/test.log', 'a') as log:
    log.writelines('say something...')
    

In [44]:
d2_arr = np.random.randint(0, 10, size=(10, 10))
print(d2_arr)
print(d2_arr[[[1,2], [3,4]]])

[[0 1 1 4 3 5 7 4 6 8]
 [8 9 2 8 7 5 6 9 3 0]
 [8 0 4 7 4 4 9 4 2 0]
 [3 5 8 0 2 7 0 8 1 4]
 [0 9 2 4 2 8 8 9 8 1]
 [2 4 0 5 0 7 4 0 1 7]
 [4 2 0 0 6 5 9 8 8 6]
 [3 1 8 9 1 9 2 7 0 4]
 [7 8 9 7 3 1 0 5 1 8]
 [1 5 3 2 6 2 1 5 4 3]]
[8 4]


In [47]:
who

CLEAN_DATA_PATH	 COMMON_WORDS_COUNTER	 DATASET_TEST_FACE	 DATASET_TEST_INTERACTION	 DATASET_TEST_TEXT	 DATASET_TRAIN_FACE	 DATASET_TRAIN_INTERACTION	 DATASET_TRAIN_TEXT	 DATA_HOUSE_PATH	 
EMBEDDINGS	 NUM_FACE_FEATURE	 PHOTO_TOPIC	 RAW_DATA_PATH	 TEST_PHOTO_EXAMPLE_WITH_TOPIC	 TRAIN_PHOTO_EXAMPLE_WITH_TOPIC	 arg_sort	 arr	 build_photo_examples	 
columns	 common_word_idx_map	 common_words_counter	 counts	 d2_arr	 embeddings	 json	 labels	 log	 
logger	 main	 np	 os	 path	 pd	 photo_topic	 photo_topic_map	 plt	 
r_arr	 store	 top20	 train_interaction	 unique	 users	 


In [52]:
print(r_arr)
r_arr[[3,1,2]]

[3 8 7 3 2 7 5 7 3 1 9 7 7 7 2 0 7 6 8 8]


array([3, 8, 7])

In [54]:
[3,8,7][[1,2]]

TypeError: list indices must be integers or slices, not list

In [2]:
from matplotlib import pyplot as plt
import numpy as np

In [4]:
x = np.arange(0, 1, 0.01)
rs = [1, 3, 9]
c = ['r', 'g', 'b']
y = np.ndarray(shape=(len(rs), len(x)))
for idx, r in enumerate(rs):
    y[idx] = 1 - (1 - x**r)**r
    plt.plot(x, y[idx], c[idx])
plt.show()

In [22]:
import pandas as pd

epslon = 1.0e-6


def and_or_scaling(x, r=3):
    return 1 - (1 - x**r)**r


def and_or_metric(prediction: pd.DataFrame):
    if ('user_id' not in prediction.columns) \
            or ('click_probability' not in prediction.columns):
        print('input is invalid!')
        return
    shift_max = prediction.groupby('user_id')['click_probability'].max().to_dict()
    shift_min = prediction.groupby('user_id')['click_probability'].min().to_dict()
    prediction['click_probability'] = prediction.apply(
        lambda x: (x[2] - shift_min.get(x[0], 0))
                    / (shift_max.get(x[0], 1) - shift_min.get(x[0], 0) if shift_max.get(x[0], 1) - shift_min.get(x[0], 0) != 0 else x[2]), axis=1)
    prediction['click_probability'] = and_or_scaling(prediction['click_probability'])
    return prediction



In [26]:
preds = pd.DataFrame()
preds['user_id'] = np.random.randint(0, 10, size=(100))
preds['photo_id'] = np.random.randint(0, 10, size=(100))
preds['click_probability'] = np.random.rand(100)
preds

<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

    .dataframe thead th {
        text-align: left;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>user_id</th>
      <th>photo_id</th>
      <th>click_probability</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>0</td>
      <td>3</td>
      <td>0.413710</td>
    </tr>
    <tr>
      <th>1</th>
      <td>0</td>
      <td>9</td>
      <td>0.430290</td>
    </tr>
    <tr>
      <th>2</th>
      <td>9</td>
      <td>8</td>
      <td>0.084371</td>
    </tr>
    <tr>
      <th>3</th>
      <td>3</td>
      <td>0</td>
      <td>0.919610</td>
    </tr>
    <tr>
      <th>4</th>
      <td>9</td>
      <td>7</td>
      <td>0.431947</td>
    </tr>
    <tr>
      <th>5</th>
      <td>0</td>
      <td>0</td>
      <td>0.460271</td>
    </tr>
    <tr>
      <th>6</th>
      <td>4</td>
      <td>4</td>
      <td>0.476007</td>
    </tr>
    <tr>
      <th>7</th>
      <td>8</td>
      <td>3</td>
      <td>0.324130</td>
    </tr>
    <tr>
      <th>8</th>
      <td>4</td>
      <td>6</td>
      <td>0.870673</td>
    </tr>
    <tr>
      <th>9</th>
      <td>0</td>
      <td>3</td>
      <td>0.090421</td>
    </tr>
    <tr>
      <th>10</th>
      <td>8</td>
      <td>7</td>
      <td>0.845141</td>
    </tr>
    <tr>
      <th>11</th>
      <td>9</td>
      <td>8</td>
      <td>0.894698</td>
    </tr>
    <tr>
      <th>12</th>
      <td>7</td>
      <td>3</td>
      <td>0.683414</td>
    </tr>
    <tr>
      <th>13</th>
      <td>9</td>
      <td>2</td>
      <td>0.428069</td>
    </tr>
    <tr>
      <th>14</th>
      <td>7</td>
      <td>2</td>
      <td>0.502158</td>
    </tr>
    <tr>
      <th>15</th>
      <td>6</td>
      <td>4</td>
      <td>0.107270</td>
    </tr>
    <tr>
      <th>16</th>
      <td>1</td>
      <td>3</td>
      <td>0.111853</td>
    </tr>
    <tr>
      <th>17</th>
      <td>2</td>
      <td>8</td>
      <td>0.391595</td>
    </tr>
    <tr>
      <th>18</th>
      <td>1</td>
      <td>0</td>
      <td>0.784027</td>
    </tr>
    <tr>
      <th>19</th>
      <td>4</td>
      <td>3</td>
      <td>0.343875</td>
    </tr>
    <tr>
      <th>20</th>
      <td>2</td>
      <td>1</td>
      <td>0.052016</td>
    </tr>
    <tr>
      <th>21</th>
      <td>0</td>
      <td>8</td>
      <td>0.033466</td>
    </tr>
    <tr>
      <th>22</th>
      <td>4</td>
      <td>0</td>
      <td>0.839704</td>
    </tr>
    <tr>
      <th>23</th>
      <td>8</td>
      <td>7</td>
      <td>0.134268</td>
    </tr>
    <tr>
      <th>24</th>
      <td>0</td>
      <td>0</td>
      <td>0.342246</td>
    </tr>
    <tr>
      <th>25</th>
      <td>2</td>
      <td>4</td>
      <td>0.309125</td>
    </tr>
    <tr>
      <th>26</th>
      <td>5</td>
      <td>6</td>
      <td>0.945443</td>
    </tr>
    <tr>
      <th>27</th>
      <td>5</td>
      <td>3</td>
      <td>0.988260</td>
    </tr>
    <tr>
      <th>28</th>
      <td>6</td>
      <td>0</td>
      <td>0.444454</td>
    </tr>
    <tr>
      <th>29</th>
      <td>6</td>
      <td>1</td>
      <td>0.910692</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>70</th>
      <td>3</td>
      <td>6</td>
      <td>0.864754</td>
    </tr>
    <tr>
      <th>71</th>
      <td>8</td>
      <td>1</td>
      <td>0.230794</td>
    </tr>
    <tr>
      <th>72</th>
      <td>8</td>
      <td>5</td>
      <td>0.006597</td>
    </tr>
    <tr>
      <th>73</th>
      <td>0</td>
      <td>0</td>
      <td>0.276246</td>
    </tr>
    <tr>
      <th>74</th>
      <td>0</td>
      <td>5</td>
      <td>0.616268</td>
    </tr>
    <tr>
      <th>75</th>
      <td>3</td>
      <td>9</td>
      <td>0.039892</td>
    </tr>
    <tr>
      <th>76</th>
      <td>8</td>
      <td>1</td>
    

In [28]:
and_or_metric(preds)

<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

    .dataframe thead th {
        text-align: left;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>user_id</th>
      <th>photo_id</th>
      <th>click_probability</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>0</td>
      <td>3</td>
      <td>3.913729e-02</td>
    </tr>
    <tr>
      <th>1</th>
      <td>0</td>
      <td>9</td>
      <td>5.511067e-02</td>
    </tr>
    <tr>
      <th>2</th>
      <td>9</td>
      <td>8</td>
      <td>0.000000e+00</td>
    </tr>
    <tr>
      <th>3</th>
      <td>3</td>
      <td>0</td>
      <td>1.000000e+00</td>
    </tr>
    <tr>
      <th>4</th>
      <td>9</td>
      <td>7</td>
      <td>3.009879e-02</td>
    </tr>
    <tr>
      <th>5</th>
      <td>0</td>
      <td>0</td>
      <td>9.710118e-02</td>
    </tr>
    <tr>
      <th>6</th>
      <td>4</td>
      <td>4</td>
      <td>8.522185e-02</td>
    </tr>
    <tr>
      <th>7</th>
      <td>8</td>
      <td>3</td>
      <td>1.096163e-02</td>
    </tr>
    <tr>
      <th>8</th>
      <td>4</td>
      <td>6</td>
      <td>1.000000e+00</td>
    </tr>
    <tr>
      <th>9</th>
      <td>0</td>
      <td>3</td>
      <td>1.953595e-09</td>
    </tr>
    <tr>
      <th>10</th>
      <td>8</td>
      <td>7</td>
      <td>1.000000e+00</td>
    </tr>
    <tr>
      <th>11</th>
      <td>9</td>
      <td>8</td>
      <td>1.000000e+00</td>
    </tr>
    <tr>
      <th>12</th>
      <td>7</td>
      <td>3</td>
      <td>2.472681e-01</td>
    </tr>
    <tr>
      <th>13</th>
      <td>9</td>
      <td>2</td>
      <td>2.745025e-02</td>
    </tr>
    <tr>
      <th>14</th>
      <td>7</td>
      <td>2</td>
      <td>0.000000e+00</td>
    </tr>
    <tr>
      <th>15</th>
      <td>6</td>
      <td>4</td>
      <td>0.000000e+00</td>
    </tr>
    <tr>
      <th>16</th>
      <td>1</td>
      <td>3</td>
      <td>1.772560e-07</td>
    </tr>
    <tr>
      <th>17</th>
      <td>2</td>
      <td>8</td>
      <td>1.497291e-02</td>
    </tr>
    <tr>
      <th>18</th>
      <td>1</td>
      <td>0</td>
      <td>9.990568e-01</td>
    </tr>
    <tr>
      <th>19</th>
      <td>4</td>
      <td>3</td>
      <td>2.963113e-03</td>
    </tr>
    <tr>
      <th>20</th>
      <td>2</td>
      <td>1</td>
      <td>0.000000e+00</td>
    </tr>
    <tr>
      <th>21</th>
      <td>0</td>
      <td>8</td>
      <td>0.000000e+00</td>
    </tr>
    <tr>
      <th>22</th>
      <td>4</td>
      <td>0</td>
      <td>9.999920e-01</td>
    </tr>
    <tr>
      <th>23</th>
      <td>8</td>
      <td>7</td>
      <td>3.523546e-06</td>
    </tr>
    <tr>
      <th>24</th>
      <td>0</td>
      <td>0</td>
      <td>6.867780e-03</td>
    </tr>
    <tr>
      <th>25</th>
      <td>2</td>
      <td>4</td>
      <td>1.365392e-03</td>
    </tr>
    <tr>
      <th>26</th>
      <td>5</td>
      <td>6</td>
      <td>9.999929e-01</td>
    </tr>
    <tr>
      <th>27</th>
      <td>5</td>
      <td>3</td>
      <td>1.000000e+00</td>
    </tr>
    <tr>
      <th>28</th>
      <td>6</td>
      <td>0</td>
      <td>2.591217e-02</td>
    </tr>
    <tr>
      <th>29</th>
      <td>6</td>
      <td>1</td>
      <td>1.000000e+00</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>70</th>
      <td>3</td>
      <td>6</td>
      <td>9.999958e-01</td>
    </tr>
    <tr>
      <th>71</th>
      <td>8</td>
      <td>1</td>
      <td>5.337840e-04</td>
    </tr>
    <tr>
      <th>72</th>
      <td>8</td>
      <td>5</td>
      <td>0.000000e+00</td>
    </tr>
    <tr>
      <th>73</th>
      <td>0</td>
      <td>0</td>
      <td>8.491130e-04</td>
    </tr>
    <tr>
      <th>74</th>
      <td>0</td>
      <td>5</td>
      <td>6.600970e-01</td>
    </tr>
    <tr>
      <th>7