In [7]:
from preprocessing_photos import *

In [3]:
import pandas as pd

In [10]:
path = RAW_DATA_PATH
DATASET_TRAIN_INTERACTION = 'train_interaction.txt'
columns = ['user_id', 'photo_id', 'click', 'like', 'follow', 'time', 'playing_time', 'duration_time']
train_interaction = pd.read_table(os.path.join(path, DATASET_TRAIN_INTERACTION), header=None)
train_interaction.columns = columns
users = set(train_interaction['user_id'])
print(len(users))
labels = np.any(train_interaction[['click', 'like', 'follow']], axis=1)
print('#pos={}, #tot={}, ratio={}%'.format(np.sum(labels), len(labels), np.sum(labels)/len(labels) * 100))

37821


#pos=10547052, #tot=52134536, ratio=20.230451461196473%


In [24]:
from matplotlib import pyplot as plt
unique, counts = np.unique(train_interaction['user_id'], return_counts=True)
plt.hist(counts, bins=len(unique), range=[0, 5000])
plt.show()

In [25]:
plt.hist(counts, bins=len(unique), range=[0, 5000])
plt.show()

In [26]:
import numpy as np

In [29]:
r_arr = np.random.randint(0, 10, 20)
print(r_arr)
arg_sort = np.argsort(r_arr)
print(arg_sort)
top20 = arg_sort[int(len(r_arr) * 0.8):]
print(top20)
print(r_arr[top20])


[3 8 7 3 2 7 5 7 3 1 9 7 7 7 2 0 7 6 8 8]
[15  9 14  4  8  0  3  6 17  7 11 12 13  2 16  5 18  1 19 10]
[18  1 19 10]
[8 8 8 9]
