In [7]:
from preprocessing_photos import *

In [3]:
import pandas as pd

In [10]:
path = RAW_DATA_PATH
DATASET_TRAIN_INTERACTION = 'train_interaction.txt'
columns = ['user_id', 'photo_id', 'click', 'like', 'follow', 'time', 'playing_time', 'duration_time']
train_interaction = pd.read_table(os.path.join(path, DATASET_TRAIN_INTERACTION), header=None)
train_interaction.columns = columns
users = set(train_interaction['user_id'])
print(len(users))
labels = np.any(train_interaction[['click', 'like', 'follow']], axis=1)
print('#pos={}, #tot={}, ratio={}%'.format(np.sum(labels), len(labels), np.sum(labels)/len(labels) * 100))

37821


#pos=10547052, #tot=52134536, ratio=20.230451461196473%


In [24]:
from matplotlib import pyplot as plt
unique, counts = np.unique(train_interaction['user_id'], return_counts=True)
plt.hist(counts, bins=len(unique), range=[0, 5000])
plt.show()

In [25]:
plt.hist(counts, bins=len(unique), range=[0, 5000])
plt.show()

In [26]:
import numpy as np

In [29]:
r_arr = np.random.randint(0, 10, 20)
print(r_arr)
arg_sort = np.argsort(r_arr)
print(arg_sort)
top20 = arg_sort[int(len(r_arr) * 0.8):]
print(top20)
print(r_arr[top20])


[3 8 7 3 2 7 5 7 3 1 9 7 7 7 2 0 7 6 8 8]
[15  9 14  4  8  0  3  6 17  7 11 12 13  2 16  5 18  1 19 10]
[18  1 19 10]
[8 8 8 9]


In [40]:
with open('datahouse/test.log', 'a') as log:
    log.writelines('say something...')
    

In [44]:
d2_arr = np.random.randint(0, 10, size=(10, 10))
print(d2_arr)
print(d2_arr[[[1,2], [3,4]]])

[[0 1 1 4 3 5 7 4 6 8]
 [8 9 2 8 7 5 6 9 3 0]
 [8 0 4 7 4 4 9 4 2 0]
 [3 5 8 0 2 7 0 8 1 4]
 [0 9 2 4 2 8 8 9 8 1]
 [2 4 0 5 0 7 4 0 1 7]
 [4 2 0 0 6 5 9 8 8 6]
 [3 1 8 9 1 9 2 7 0 4]
 [7 8 9 7 3 1 0 5 1 8]
 [1 5 3 2 6 2 1 5 4 3]]
[8 4]


In [47]:
who

CLEAN_DATA_PATH	 COMMON_WORDS_COUNTER	 DATASET_TEST_FACE	 DATASET_TEST_INTERACTION	 DATASET_TEST_TEXT	 DATASET_TRAIN_FACE	 DATASET_TRAIN_INTERACTION	 DATASET_TRAIN_TEXT	 DATA_HOUSE_PATH	 
EMBEDDINGS	 NUM_FACE_FEATURE	 PHOTO_TOPIC	 RAW_DATA_PATH	 TEST_PHOTO_EXAMPLE_WITH_TOPIC	 TRAIN_PHOTO_EXAMPLE_WITH_TOPIC	 arg_sort	 arr	 build_photo_examples	 
columns	 common_word_idx_map	 common_words_counter	 counts	 d2_arr	 embeddings	 json	 labels	 log	 
logger	 main	 np	 os	 path	 pd	 photo_topic	 photo_topic_map	 plt	 
r_arr	 store	 top20	 train_interaction	 unique	 users	 


In [52]:
print(r_arr)
r_arr[[3,1,2]]

[3 8 7 3 2 7 5 7 3 1 9 7 7 7 2 0 7 6 8 8]


array([3, 8, 7])

In [ ]:
[3,8,7][[1,2]]

[8]